# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

df["species"] = [
    iris.target_names[i]
    for i in iris.target
]

sns.set_style("whitegrid")

print("Dataset Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nFirst 5 Rows:")
print(df.head())

num_cols = df.select_dtypes(include=['int64', 'float64']).columns
for col in num_cols:
    plt.figure(figsize=(6,4))
    sns.histplot(df[col], kde=True, color="skyblue")
    plt.title(f"Histogram of {col}")
    plt.xlabel(col)
    plt.ylabel("Frequency")
    plt.show()
for col in num_cols:
    plt.figure(figsize=(6,4))
    sns.boxplot(x=df[col], color="orange")
    plt.title(f"Boxplot of {col}")
    plt.show()

plt.figure(figsize=(8,6))
sns.heatmap(
    df[num_cols].corr(),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")
plt.show()

sns.pairplot(df, hue="species")
plt.show()

plt.figure(figsize=(6,4))

sns.scatterplot(
    data=df,
    x=num_cols[0],
    y=num_cols[1],
    hue="species"
)

plt.title(f"{num_cols[0]} vs {num_cols[1]}")
plt.show()
plt.figure(figsize=(6,4))

df["species"].value_counts().plot(
    kind="bar",
    color=["red", "green", "blue"]
)

plt.title("Species Count")
plt.xlabel("Species")
plt.ylabel("Count")
plt.show()
plt.figure(figsize=(6,6))

df["species"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%"
)

plt.title("Species Distribution")
plt.ylabel("")
plt.show()
plt.figure(figsize=(8,4))

plt.plot(df[num_cols[0]], color="purple")

plt.title(f"Trend of {num_cols[0]}")
plt.xlabel("Index")
plt.ylabel(num_cols[0])
plt.show()


print("\nData Visualization Completed Successfully!")
print("Charts Generated:")
print("✔ Histogram")
print("✔ Box Plot")
print("✔ Correlation Heatmap")
print("✔ Pair Plot")
print("✔ Scatter Plot")
print("✔ Bar Chart")
print("✔ Pie Chart")
print("✔ Line Chart")